import { assertElement } from '../shared/dom';

export const patchElements = {
  workspace: assertElement(document.querySelector<HTMLElement>('.workspace'), 'workspace'),
  operatorFooter: assertElement(document.querySelector<HTMLElement>('.operator-footer'), 'operatorFooter'),
  timecode: assertElement(document.querySelector<HTMLDivElement>('#timecode'), 'timecode'),
  showStatus: assertElement(document.querySelector<HTMLDivElement>('#showStatus'), 'showStatus'),
  issueList: assertElement(document.querySelector<HTMLDivElement>('#issueList'), 'issueList'),
  mediaPoolPanel: assertElement(document.querySelector<HTMLElement>('#mediaPoolPanel'), 'mediaPoolPanel'),
  visualList: assertElement(document.querySelector<HTMLDivElement>('#visualList'), 'visualList'),
  audioPanel: assertElement(document.querySelector<HTMLDivElement>('#audioPanel'), 'audioPanel'),
  displayList: assertElement(document.querySelector<HTMLDivElement>('#displayList'), 'displayList'),
  outputPanel: assertElement(document.querySelector<HTMLDivElement>('#outputPanel'), 'outputPanel'),
  workspaceSplitter: assertElement(document.querySelector<HTMLDivElement>('#workspaceSplitter'), 'workspaceSplitter'),
  mainFooterSplitter: assertElement(document.querySelector<HTMLDivElement>('#mainFooterSplitter'), 'mainFooterSplitter'),
  footerSplitter: assertElement(document.querySelector<HTMLDivElement>('#footerSplitter'), 'footerSplitter'),
  assetPreviewSplitter: assertElement(document.querySelector<HTMLDivElement>('#assetPreviewSplitter'), 'assetPreviewSplitter'),
  detailsContent: assertElement(document.querySelector<HTMLDivElement>('#detailsContent'), 'detailsContent'),
  detailsHeading: assertElement(document.querySelector<HTMLHeadingElement>('#detailsHeading'), 'detailsHeading'),
  assetPreviewRegion: assertElement(document.querySelector<HTMLDivElement>('#assetPreviewRegion'), 'assetPreviewRegion'),
  assetPreview: assertElement(document.querySelector<HTMLDivElement>('#assetPreview'), 'assetPreview'),
  liveState: assertElement(document.querySelector<HTMLSpanElement>('#liveState'), 'liveState'),
  playButton: assertElement(document.querySelector<HTMLButtonElement>('#playButton'), 'playButton'),
  pauseButton: assertElement(document.querySelector<HTMLButtonElement>('#pauseButton'), 'pauseButton'),
  stopButton: assertElement(document.querySelector<HTMLButtonElement>('#stopButton'), 'stopButton'),
  loopToggleButton: assertElement(document.querySelector<HTMLButtonElement>('#loopToggleButton'), 'loopToggleButton'),
  rateDisplayButton: assertElement(document.querySelector<HTMLButtonElement>('#rateDisplayButton'), 'rateDisplayButton'),
  timelineScrubber: assertElement(document.querySelector<HTMLInputElement>('#timelineScrubber'), 'timelineScrubber'),
  timelineSummaryPrimary: assertElement(document.querySelector<HTMLDivElement>('#timelineSummaryPrimary'), 'timelineSummaryPrimary'),
  timelineLoopLimitLine: assertElement(document.querySelector<HTMLDivElement>('#timelineLoopLimitLine'), 'timelineLoopLimitLine'),
  loopStartInput: assertElement(document.querySelector<HTMLInputElement>('#loopStartInput'), 'loopStartInput'),
  loopEndInput: assertElement(document.querySelector<HTMLInputElement>('#loopEndInput'), 'loopEndInput'),
  loopActivateButton: assertElement(document.querySelector<HTMLButtonElement>('#loopActivateButton'), 'loopActivateButton'),
  loopPopover: assertElement(document.querySelector<HTMLDivElement>('#loopPopover'), 'loopPopover'),
  visualTabButton: assertElement(document.querySelector<HTMLButtonElement>('#visualTabButton'), 'visualTabButton'),
  audioTabButton: assertElement(document.querySelector<HTMLButtonElement>('#audioTabButton'), 'audioTabButton'),
  poolSearchInput: assertElement(document.querySelector<HTMLInputElement>('#poolSearchInput'), 'poolSearchInput'),
  poolSortSelect: assertElement(document.querySelector<HTMLSelectElement>('#poolSortSelect'), 'poolSortSelect'),
  saveShowButton: assertElement(document.querySelector<HTMLButtonElement>('#saveShowButton'), 'saveShowButton'),
  saveShowAsButton: assertElement(document.querySelector<HTMLButtonElement>('#saveShowAsButton'), 'saveShowAsButton'),
  openShowButton: assertElement(document.querySelector<HTMLButtonElement>('#openShowButton'), 'openShowButton'),
  createShowButton: assertElement(document.querySelector<HTMLButtonElement>('#createShowButton'), 'createShowButton'),
  addVisualsButton: assertElement(document.querySelector<HTMLButtonElement>('#addVisualsButton'), 'addVisualsButton'),
  createOutputButton: assertElement(document.querySelector<HTMLButtonElement>('#createOutputButton'), 'createOutputButton'),
  refreshOutputsButton: assertElement(document.querySelector<HTMLButtonElement>('#refreshOutputsButton'), 'refreshOutputsButton'),
  expandMixerButton: assertElement(document.querySelector<HTMLButtonElement>('#expandMixerButton'), 'expandMixerButton'),
  clearSoloButton: assertElement(document.querySelector<HTMLButtonElement>('#clearSoloButton'), 'clearSoloButton'),
  resetMetersButton: assertElement(document.querySelector<HTMLButtonElement>('#resetMetersButton'), 'resetMetersButton'),
  globalAudioMuteButton: assertElement(document.querySelector<HTMLButtonElement>('#globalAudioMuteButton'), 'globalAudioMuteButton'),
  displayBlackoutButton: assertElement(document.querySelector<HTMLButtonElement>('#displayBlackoutButton'), 'displayBlackoutButton'),
  performanceModeButton: assertElement(document.querySelector<HTMLButtonElement>('#performanceModeButton'), 'performanceModeButton'),
  runtimeVersionLabel: assertElement(document.querySelector<HTMLSpanElement>('#runtimeVersionLabel'), 'runtimeVersionLabel'),
  createDisplayButton: assertElement(document.querySelector<HTMLButtonElement>('#createDisplayButton'), 'createDisplayButton'),
};

export type PatchElements = typeof patchElements;
